farmers_market/checkout/urls.py
from django.conf.urls import url

from checkout.views import CheckoutView

app_name = 'checkout'

urlpatterns = [
    url(r'^$', CheckoutView.as_view(), name='index')
]

farmers_market/farmers_market/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.views.generic import TemplateView

urlpatterns = [
    path(r'checkout/', include('checkout.urls')),
    path('admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='index.html')),
]

farmers_market/farmers_market/templates/base.html
{% comment %}
Farmers Market App base template.
{% endcomment %}
<!doctype html>
<html lang="en">
  <head>
    <title>Welcome to the ObjectRocket Farmer's Market</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% block css %}
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    {% endblock %}
  </head>
  <body>
    <div class="container">
      <h1>Welcome to the <strong>ObjectRocket</strong> Farmer's Market!</h1>
      {% block content %}{% endblock content %}
    </div>

    {% block js %}
    <!-- Bootstrap4 Scripts -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    {% endblock %}
  </body>
</html>

farmers_market/farmers_market/templates/index.html
{% extends "base.html" %}

{% comment %}
Template for the Root Index Page
{% endcomment %}

{% load checkout_tags %}

{% block content %}
<div class="container">
  <h2>Select a function below:</h2>
  <ul>
    <li class="display-4"><a href="{% url 'checkout:index' %}">Checkout</a></li>
  </ul>
</div>
{% endblock content %}